INSERT INTO
    Kubs.Helper_Months (MonthNum, MonthName_PL)
VALUES
    (1, 'Styczen'),
    (2, 'Luty'),
    (3, 'Marzec'),
    (4, 'Kwiecien'),
    (5, 'Maj'),
    (6, 'Czerwiec'),
    (7, 'Lipiec'),
    (8, 'Sierpien'),
    (9, 'Wrzesien'),
    (10, 'Pazdziernik'),
    (11, 'Listopad'),
    (12, 'Grudzien');

INSERT INTO
    Kubs.Helper_Weekdays (WeekdayNum, WeekdayName_PL)
VALUES
    (1, 'Niedziela'),
    (2, 'Poniedzialek'),
    (3, 'Wtorek'),
    (4, 'Sroda'),
    (5, 'Czwartek'),
    (6, 'Piatek'),
    (7, 'Sobota');

INSERT INTO
    Kubs.Helper_Titles (SourceTitle, StandardTitle)
VALUES
    ('Mr.', 'Mr.'),
    ('Ms', 'Ms.'),
    ('Ms.', 'Ms.'),
    ('Mrs.', 'Mrs.'),
    ('Sra', 'Sr.'),
    ('Sr.', 'Sr.');

INSERT INTO
    Kubs.Helper_ProductNames (CleanName)
VALUES
    ('All-Purpose Bike Stand'),
    ('AWC Logo Cap'),
    ('Bike Wash - Dissolver'),
    ('Cable Lock'),
    ('Chain'),
    ('Classic Vest'),
    ('Fender Set - Mountain'),
    ('Front Brakes'),
    ('Front Derailleur'),
    ('Full-Finger Gloves'),
    ('Half-Finger Gloves'),
    ('Hitch Rack - 4-Bike'),
    ('HL Bottom Bracket'),
    ('HL Crankset'),
    ('HL Fork'),
    ('HL Headset'),
    ('HL Mountain Frame - Black'),
    ('HL Mountain Frame - Silver'),
    ('HL Mountain Front Wheel'),
    ('HL Mountain Handlebars'),
    ('HL Mountain Pedal'),
    ('HL Mountain Rear Wheel'),
    ('HL Mountain Seat/Saddle'),
    ('HL Mountain Tire'),
    ('HL Road Frame - Black'),
    ('HL Road Frame - Red'),
    ('HL Road Front Wheel'),
    ('HL Road Handlebars'),
    ('HL Road Pedal'),
    ('HL Road Rear Wheel'),
    ('HL Road Seat/Saddle'),
    ('HL Road Tire'),
    ('HL Touring Frame - Blue'),
    ('HL Touring Frame - Yellow'),
    ('HL Touring Handlebars'),
    ('HL Touring Seat/Saddle'),
    ('Hydration Pack - 70 oz.'),
    ('LL Bottom Bracket'),
    ('LL Crankset'),
    ('LL Fork'),
    ('LL Headset'),
    ('LL Mountain Frame - Black'),
    ('LL Mountain Frame - Silver'),
    ('LL Mountain Front Wheel'),
    ('LL Mountain Handlebars'),
    ('LL Mountain Pedal'),
    ('LL Mountain Rear Wheel'),
    ('LL Mountain Seat/Saddle'),
    ('LL Mountain Tire'),
    ('LL Road Frame - Black'),
    ('LL Road Frame - Red'),
    ('LL Road Handlebars'),
    ('LL Road Pedal'),
    ('LL Road Rear Wheel'),
    ('LL Road Seat/Saddle'),
    ('LL Road Tire'),
    ('LL Touring Frame - Blue'),
    ('LL Touring Frame - Yellow'),
    ('LL Touring Handlebars'),
    ('LL Touring Seat/Saddle'),
    ('Long-Sleeve Logo Jersey'),
    ('Men''s Bib-Shorts'),
    ('Men''s Sports Shorts'),
    ('Minipump'),
    ('ML Crankset'),
    ('ML Headset'),
    ('ML Mountain Frame - Black'),
    ('ML Mountain Frame-W - Silver'),
    ('ML Mountain Front Wheel'),
    ('ML Mountain Handlebars'),
    ('ML Mountain Pedal'),
    ('ML Mountain Rear Wheel'),
    ('ML Mountain Seat/Saddle'),
    ('ML Mountain Tire'),
    ('ML Road Frame - Red'),
    ('ML Road Frame-W - Yellow'),
    ('ML Road Front Wheel'),
    ('ML Road Pedal'),
    ('ML Road Rear Wheel'),
    ('ML Road Tire'),
    ('ML Touring Seat/Saddle'),
    ('Mountain Bike Socks'),
    ('Mountain Bottle Cage'),
    ('Mountain Tire Tube'),
    ('Mountain-100 Black'),
    ('Mountain-100 Silver'),
    ('Mountain-200 Black'),
    ('Mountain-200 Silver'),
    ('Mountain-300 Black'),
    ('Mountain-400-W Silver'),
    ('Mountain-500 Black'),
    ('Mountain-500 Silver'),
    ('Patch Kit/8 Patches'),
    ('Racing Socks'),
    ('Rear Brakes'),
    ('Rear Derailleur'),
    ('Road Bottle Cage'),
    ('Road Tire Tube'),
    ('Road-150 Red'),
    ('Road-250 Black'),
    ('Road-250 Red'),
    ('Road-350-W Yellow'),
    ('Road-450 Red'),
    ('Road-550-W Yellow'),
    ('Road-650 Black'),
    ('Road-650 Red'),
    ('Road-750 Black'),
    ('Short-Sleeve Classic Jersey'),
    ('Sport-100 Helmet, Black'),
    ('Sport-100 Helmet, Blue'),
    ('Sport-100 Helmet, Red'),
    ('Touring Pedal'),
    ('Touring Tire'),
    ('Touring Tire Tube'),
    ('Touring-1000 Blue'),
    ('Touring-1000 Yellow'),
    ('Touring-2000 Blue'),
    ('Touring-3000 Blue'),
    ('Touring-3000 Yellow'),
    ('Water Bottle - 30 oz.'),
    ('Women''s Mountain Shorts'),
    ('Women''s Tights');