CREATE TABLE Helper_Months (
    MonthNum INT PRIMARY KEY,
    MonthName NVARCHAR(20) NOT NULL
);

INSERT INTO
    Helper_Months (MonthNum, MonthName)
VALUES
    (1, 'January'),
    (2, 'February'),
    (3, 'March'),
    (4, 'April'),
    (5, 'May'),
    (6, 'June'),
    (7, 'July'),
    (8, 'August'),
    (9, 'September'),
    (10, 'October'),
    (11, 'November'),
    (12, 'December');

CREATE TABLE Helper_Weekdays (
    WeekdayNum INT PRIMARY KEY,
    WeekdayName NVARCHAR(20) NOT NULL
);

INSERT INTO
    Helper_Weekdays (WeekdayNum, WeekdayName)
VALUES
    (1, 'Sunday'),
    (2, 'Monday'),
    (3, 'Tuesday'),
    (4, 'Wednesday'),
    (5, 'Thursday'),
    (6, 'Friday'),
    (7, 'Saturday');

CREATE TABLE Helper_CountryContinents (
    CountryName NVARCHAR(100) PRIMARY KEY,
    Continent NVARCHAR(50) NOT NULL
);

INSERT INTO
    Helper_CountryContinents (CountryName, Continent)
VALUES
    ('Andorra', 'Europe'),
    ('Argentina', 'South America'),
    ('Australia', 'Oceania'),
    ('Austria', 'Europe'),
    ('Azerbaijan', 'Asia'),
    ('Bahrain', 'Asia'),
    ('Belgium', 'Europe'),
    ('Brazil', 'South America'),
    ('Bulgaria', 'Europe'),
    ('Canada', 'North America'),
    ('Chile', 'South America'),
    ('China', 'Asia'),
    ('Colombia', 'South America'),
    ('Croatia', 'Europe'),
    ('Czech Republic', 'Europe'),
    ('Denmark', 'Europe'),
    ('Estonia', 'Europe'),
    ('Finland', 'Europe'),
    ('France', 'Europe'),
    ('Georgia', 'Asia'),
    ('Germany', 'Europe'),
    ('Hungary', 'Europe'),
    ('India', 'Asia'),
    ('Indonesia', 'Asia'),
    ('Italy', 'Europe'),
    ('Japan', 'Asia'),
    ('Korea', 'Asia'),
    ('Liechtenstein', 'Europe'),
    ('Malaysia', 'Asia'),
    ('Malta', 'Europe'),
    ('Mexico', 'North America'),
    ('Monaco', 'Europe'),
    ('Morocco', 'Africa'),
    ('Netherlands', 'Europe'),
    ('New Zealand', 'Oceania'),
    ('Poland', 'Europe'),
    ('Portugal', 'Europe'),
    ('Qatar', 'Asia'),
    ('Russia', 'Europe'),
    ('Saudi Arabia', 'Asia'),
    ('Serbia', 'Europe'),
    ('Singapore', 'Asia'),
    ('Slovakia', 'Europe'),
    ('South Africa', 'Africa'),
    ('Spain', 'Europe'),
    ('Sweden', 'Europe'),
    ('Switzerland', 'Europe'),
    ('Thailand', 'Asia'),
    ('Turkey', 'Asia'),
    ('UAE', 'Asia'),
    ('UK', 'Europe'),
    ('USA', 'North America'),
    ('Ukraine', 'Europe'),
    ('Uruguay', 'South America'),
    ('Venezuela', 'South America'),
    ('Zimbabwe', 'Africa');

CREATE TABLE Helper_NationalityCountries (
    Nationality NVARCHAR(100) PRIMARY KEY,
    CountryName NVARCHAR(100) NOT NULL
);

INSERT INTO
    Helper_NationalityCountries (Nationality, CountryName)
VALUES
    ('American', 'USA'),
    ('American-Italian', 'USA'),
    ('Andorran', 'Andorra'),
    ('Argentine', 'Argentina'),
    ('Argentine-Italian', 'Argentina'),
    ('Argentinian', 'Argentina'),
    ('Australian', 'Australia'),
    ('Austrian', 'Austria'),
    ('Azerbaijani', 'Azerbaijan'),
    ('Belgian', 'Belgium'),
    ('Brazilian', 'Brazil'),
    ('British', 'UK'),
    ('Bulgarian', 'Bulgaria'),
    ('Canadian', 'Canada'),
    ('Chilean', 'Chile'),
    ('Chinese', 'China'),
    ('Colombian', 'Colombia'),
    ('Croatian', 'Croatia'),
    ('Czech', 'Czech Republic'),
    ('Danish', 'Denmark'),
    ('Dutch', 'Netherlands'),
    ('East German', 'Germany'),
    ('Emirati', 'UAE'),
    ('Estonian', 'Estonia'),
    ('Finnish', 'Finland'),
    ('French', 'France'),
    ('Georgian', 'Georgia'),
    ('German', 'Germany'),
    ('Hong Kong', 'China'),
    ('Hungarian', 'Hungary'),
    ('Indian', 'India'),
    ('Indonesian', 'Indonesia'),
    ('Irish', 'UK'),
    ('Italian', 'Italy'),
    ('Japanese', 'Japan'),
    ('Liechtensteiner', 'Liechtenstein'),
    ('Malaysian', 'Malaysia'),
    ('Maltese', 'Malta'),
    ('Mexican', 'Mexico'),
    ('Monegasque', 'Monaco'),
    ('New Zealander', 'New Zealand'),
    ('Polish', 'Poland'),
    ('Portuguese', 'Portugal'),
    ('Qatari', 'Qatar'),
    ('Rhodesian', 'South Africa'),
    ('Russian', 'Russia'),
    ('Saudi', 'Saudi Arabia'),
    ('Serbian', 'Serbia'),
    ('Slovakian', 'Slovakia'),
    ('South African', 'South Africa'),
    ('South Korean', 'Korea'),
    ('Spanish', 'Spain'),
    ('Swedish', 'Sweden'),
    ('Swiss', 'Switzerland'),
    ('Thai', 'Thailand'),
    ('Ukrainian', 'Ukraine'),
    ('Uruguayan', 'Uruguay'),
    ('Venezuelan', 'Venezuela');

CREATE TABLE Helper_StatusCategory (
    StatusText NVARCHAR(255) PRIMARY KEY,
    BroadCategory NVARCHAR(100) NOT NULL
);

INSERT INTO
    Helper_StatusCategory (StatusText, BroadCategory)
VALUES
    ('Finished', 'Race Outcome'),
    ('Disqualified', 'Sporting/Regulatory'),
    ('Accident', 'Accident/Incident'),
    ('Collision', 'Accident/Incident'),
    ('Engine', 'Mechanical Failure'),
    ('Gearbox', 'Mechanical Failure'),
    ('Transmission', 'Mechanical Failure'),
    ('Clutch', 'Mechanical Failure'),
    ('Hydraulics', 'Mechanical Failure'),
    ('Electrical', 'Mechanical Failure'),
    ('+ Lap', 'Race Outcome'),
    ('+ Laps', 'Race Outcome'),
    ('+1 Laps', 'Race Outcome'),
    ('+2 Laps', 'Race Outcome'),
    ('+3 Laps', 'Race Outcome'),
    ('+4 Laps', 'Race Outcome'),
    ('+5 Laps', 'Race Outcome'),
    ('+6 Laps', 'Race Outcome'),
    ('+7 Laps', 'Race Outcome'),
    ('+8 Laps', 'Race Outcome'),
    ('+9 Laps', 'Race Outcome'),
    ('Spun off', 'Accident/Incident'),
    ('Radiator', 'Mechanical Failure'),
    ('Suspension', 'Mechanical Failure'),
    ('Brakes', 'Mechanical Failure'),
    ('Differential', 'Mechanical Failure'),
    ('Overheating', 'Mechanical Failure'),
    ('Mechanical', 'Mechanical Failure'),
    ('Tyre', 'Mechanical Failure'),
    ('Driver Seat', 'Mechanical Failure'),
    ('Puncture', 'Mechanical Failure'),
    ('Driveshaft', 'Mechanical Failure'),
    ('Retired', 'Race Outcome'),
    ('Fuel pressure', 'Mechanical Failure'),
    ('Front wing', 'Mechanical Failure'),
    ('Water pressure', 'Mechanical Failure'),
    ('Refuelling', 'Mechanical Failure'),
    ('Wheel', 'Mechanical Failure'),
    ('Throttle', 'Mechanical Failure'),
    ('Steering', 'Mechanical Failure'),
    ('Technical', 'Mechanical Failure'),
    ('Electronics', 'Mechanical Failure'),
    ('Broken wing', 'Mechanical Failure'),
    ('Heat shield', 'Mechanical Failure'),
    ('Exhaust', 'Mechanical Failure'),
    ('Oil leak', 'Mechanical Failure'),
    ('Wheel rim', 'Mechanical Failure'),
    ('Water leak', 'Mechanical Failure'),
    ('Fuel pump', 'Mechanical Failure'),
    ('Track rod', 'Mechanical Failure'),
    ('Oil pressure', 'Mechanical Failure'),
    ('Withdrew', 'Sporting/Regulatory'),
    ('Engine fire', 'Accident/Incident'),
    ('Engine misfire', 'Mechanical Failure'),
    ('Tyre puncture', 'Mechanical Failure'),
    ('Out of fuel', 'Mechanical Failure'),
    ('Wheel nut', 'Mechanical Failure'),
    ('Not classified', 'Race Outcome'),
    ('Pneumatics', 'Mechanical Failure'),
    ('Handling', 'Mechanical Failure'),
    ('Rear wing', 'Mechanical Failure'),
    ('Fire', 'Accident/Incident'),
    ('Wheel bearing', 'Mechanical Failure'),
    ('Physical', 'Driver Issue'),
    ('Fuel system', 'Mechanical Failure'),
    ('Oil line', 'Mechanical Failure'),
    ('Fuel rig', 'Mechanical Failure'),
    ('Launch control', 'Mechanical Failure'),
    ('Injured', 'Driver Issue'),
    ('Fuel', 'Mechanical Failure'),
    ('Power loss', 'Mechanical Failure'),
    ('Vibrations', 'Mechanical Failure'),
    ('107% Rule', 'Sporting/Regulatory'),
    ('Safety', 'Sporting/Regulatory'),
    ('Drivetrain', 'Mechanical Failure'),
    ('Ignition', 'Mechanical Failure'),
    ('Did not qualify', 'Pre-Race/Qualification'),
    ('Injury', 'Driver Issue'),
    ('Chassis', 'Mechanical Failure'),
    ('Battery', 'Mechanical Failure'),
    ('Stalled', 'Mechanical Failure'),
    ('Halfshaft', 'Mechanical Failure'),
    ('Crankshaft', 'Mechanical Failure'),
    ('Safety concerns', 'Sporting/Regulatory'),
    ('Not restarted', 'Race Outcome'),
    ('Alternator', 'Mechanical Failure'),
    ('Underweight', 'Sporting/Regulatory'),
    ('Safety belt', 'Mechanical Failure'),
    ('Oil pump', 'Mechanical Failure'),
    ('Fuel leak', 'Mechanical Failure'),
    ('Excluded', 'Sporting/Regulatory'),
    ('Did not prequalify', 'Pre-Race/Qualification'),
    ('Injection', 'Mechanical Failure'),
    ('Distributor', 'Mechanical Failure'),
    ('Driver unwell', 'Driver Issue'),
    ('Turbo', 'Mechanical Failure'),
    ('CV joint', 'Mechanical Failure'),
    ('Water pump', 'Mechanical Failure'),
    ('Fatal accident', 'Accident/Incident'),
    ('Spark plug', 'Mechanical Failure'),
    ('Fuel pipe', 'Mechanical Failure'),
    ('Eye injury', 'Driver Issue'),
    ('Oil pipe', 'Mechanical Failure'),
    ('Axle', 'Mechanical Failure'),
    ('Water pipe', 'Mechanical Failure'),
    ('Magneto', 'Mechanical Failure'),
    ('Supercharger', 'Mechanical Failure'),
    ('+20 Laps', 'Race Outcome'),
    ('Collision damage', 'Accident/Incident'),
    ('Power Unit', 'Mechanical Failure'),
    ('ERS', 'Mechanical Failure'),
    ('Brake duct', 'Mechanical Failure'),
    ('Seat', 'Mechanical Failure'),
    ('Damage', 'Accident/Incident'),
    ('Debris', 'Accident/Incident'),
    ('Illness', 'Driver Issue'),
    ('Undertray', 'Mechanical Failure'),
    ('Cooling system', 'Mechanical Failure');