IF EXISTS (
    SELECT
        *
    FROM
        INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE
        CONSTRAINT_SCHEMA = 'Kubs'
        AND CONSTRAINT_NAME = 'FK_FACT_SALES_DIM_CUSTOMER'
        AND TABLE_NAME = 'FACT_SALES'
)
ALTER TABLE
    Kubs.FACT_SALES DROP CONSTRAINT FK_FACT_SALES_DIM_CUSTOMER;

IF EXISTS (
    SELECT
        *
    FROM
        INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE
        CONSTRAINT_SCHEMA = 'Kubs'
        AND CONSTRAINT_NAME = 'FK_FACT_SALES_DIM_PRODUCT'
        AND TABLE_NAME = 'FACT_SALES'
)
ALTER TABLE
    Kubs.FACT_SALES DROP CONSTRAINT FK_FACT_SALES_DIM_PRODUCT;

IF EXISTS (
    SELECT
        *
    FROM
        INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE
        CONSTRAINT_SCHEMA = 'Kubs'
        AND CONSTRAINT_NAME = 'FK_FACT_SALES_DIM_SALESPERSON'
        AND TABLE_NAME = 'FACT_SALES'
)
ALTER TABLE
    Kubs.FACT_SALES DROP CONSTRAINT FK_FACT_SALES_DIM_SALESPERSON;

DROP TABLE IF EXISTS Kubs.FACT_SALES;

DROP TABLE IF EXISTS Kubs.DIM_CUSTOMER;

DROP TABLE IF EXISTS Kubs.DIM_PRODUCT;

DROP TABLE IF EXISTS Kubs.DIM_SALESPERSON;

DROP TABLE IF EXISTS Kubs.DIM_TIME;

DROP TABLE IF EXISTS Kubs.Helper_Months;

DROP TABLE IF EXISTS Kubs.Helper_Weekdays;