ALTER TABLE
    Kubs.DIM_CUSTOMER
ADD
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CustomerID);

ALTER TABLE
    Kubs.DIM_PRODUCT
ADD
    CONSTRAINT PK_DIM_PRODUCT PRIMARY KEY (ProductID);

ALTER TABLE
    Kubs.DIM_SALESPERSON
ADD
    CONSTRAINT PK_DIM_SALESPERSON PRIMARY KEY (SalesPersonID);

ALTER TABLE
    Kubs.FACT_SALES
ADD
    CONSTRAINT FK_FACT_SALES_DIM_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES Kubs.DIM_CUSTOMER(CustomerID);

ALTER TABLE
    Kubs.FACT_SALES
ADD
    CONSTRAINT FK_FACT_SALES_DIM_PRODUCT FOREIGN KEY (ProductID) REFERENCES Kubs.DIM_PRODUCT(ProductID);

ALTER TABLE
    Kubs.FACT_SALES
ADD
    CONSTRAINT FK_FACT_SALES_DIM_SALESPERSON FOREIGN KEY (SalesPersonID) REFERENCES Kubs.DIM_SALESPERSON(SalesPersonID);